#!/bin/sh
unset LUA_PATH LUA_PATH_5_2 LUA_PATH_5_3 LUA_PATH_5_4 LUA_CPATH LUA_CPATH_5_2 LUA_CPATH_5_3 LUA_CPATH_5_4
LUAROCKS_SYSCONFDIR="/home/runner/work/hlrp/hlrp/.luarocks/etc/luarocks" LUA_PATH="/home/runner/work/hlrp/hlrp/.install/luarocks-3.3.1/src/?.lua;;" exec "/home/runner/work/hlrp/hlrp/.lua/bin/lua" "/home/runner/work/hlrp/hlrp/.install/luarocks-3.3.1/src/bin/luarocks-admin" --project-tree="/home/runner/work/hlrp/hlrp/.install/luarocks-3.3.1/lua_modules" "$@"
